### ISSUE TITLE
Website for cDock

### ISSUE THREAD

**Issue by lancelafontaine** [w0lfschild/cDock#1]
I would like to open up the idea of having a website for cDock. I recently downloaded the tool and find it very useful. However I noticed that generic SourceForge website for it. What is the authoritative repo for cDock (SourceForge or GitHub)? If GitHub, can we look into making a static GitHub website?

**Comment by w0lfschild** [comment]
Made a basic website using github pages.

w0lfschild.github.io/pages/cdock.html
