### ISSUE TITLE
El Capitan bug

### ISSUE THREAD

**Issue by Chriz007** [w0lfschild/cDock#11]
Won't let you modify or add icons to the dock.

![d7z4ao](https://cloud.githubusercontent.com/assets/12990919/8737058/2dfa50a6-2bd3-11e5-8271-1cb7dec4553b.gif)

**Comment by w0lfschild** [comment]
Yeah that's not gonna be fixed as well as any other bugs you may find with the dock.

Either revert to the actual El Capitan dock and lose theming or deal with it. You can still add apps though:

Open > Right Click > Options > Keep in Dock

**Comment by Chriz007** [comment]
What are the right steps to reset the dock? I know going into view settings and the resetting the dock thing, but it just glitches my mac up.

**Comment by w0lfschild** [comment]
https://raw.githubusercontent.com/w0lfschild/cDock/master/_resource/versionInfo.txt

**Comment by w0lfschild** [comment]
Well actually cDock might end up getting proper support for El Capitan after all. Someone else just pushed out https://github.com/mstg/Modck which is working for me with some tweaking.

Probably won't be out too soon but a functional El Capitan update should happen eventually.

**Comment by Chriz007** [comment]
Cool! I look forward to this

**Comment by w0lfschild** [comment]
Fixed in version 9 https://github.com/w0lfschild/cDock/releases/tag/v9.0

If you haven't updated El Capitan and still have the 10.10 dock you may need to restore your dock though:

    pushd /System/Library/CoreServices
    sudo mv Dock.app/ Dock_trash.app
    sudo mv Dock_bak.app/ Dock.app
    popd
    killall Dock
