### ISSUE TITLE
Menubar applet dropdown menu

### ISSUE THREAD

**Issue by dkfiresky** [w0lfschild/cDock#12]
The menubar applet dropdown menu text color does not change if running in dark mode.

![2015-07-18 16 10 23](https://cloud.githubusercontent.com/assets/2175645/8761709/e09fef32-2d67-11e5-914d-83177f208bd4.png)

**Comment by w0lfschild** [comment]
Fixed in version 9 https://github.com/w0lfschild/cDock/releases/tag/v9.0
