### ISSUE TITLE
cDock menubar applet icon

### ISSUE THREAD

**Issue by dkfiresky** [w0lfschild/cDock#13]
Can you please follow the general style of all icons in menubar, so the cDock applet icon will be monochrome and will change depending on current mode (dark/light theme)

**Comment by w0lfschild** [comment]
I'll look into it.

**Comment by dkfiresky** [comment]
Thanks :+1:

**Comment by w0lfschild** [comment]
Fixed in version 9 https://github.com/w0lfschild/cDock/releases/tag/v9.0

Using a cog for the icon at the moment though. Might change that if I can find something better.
