### ISSUE TITLE
El Capitan Beta 2 (15A225f)

### ISSUE THREAD

**Issue by dkfiresky** [w0lfschild/cDock#15]
> 10.11 requires that SIP aka "rootless" be turned off

Rootless was disabled:

```sh
$ nvram boot-args
boot-args	rootless=0
```
But cDock does not customize the Dock after pressing the "Apply" button.

The logs saying that Opee framework required:
```
7/29/15 11:33:18.824 cDock[4935]: SecTaskLoadEntitlements failed error=22
7/29/15 11:33:18.885 cDock[4935]: App did finish launching
7/29/15 11:33:30.568 Dock[5480]: Error loading /Library/Application Support/SIMBL/Plugins/cDock.bundle/Contents/MacOS/cDock:  dlopen(/Library/Application Support/SIMBL/Plugins/cDock.bundle/Contents/MacOS/cDock, 265): Library not loaded: /Library/Frameworks/Opee.framework/Versions/A/Opee
  Referenced from: /Library/Application Support/SIMBL/Plugins/cDock.bundle/Contents/MacOS/cDock
  Reason: image not found
```

Can you please provide more information on dependencies.

**Comment by w0lfschild** [comment]
Actually 9.0 was terribly crippled and didn't work at all a combination several errors made it so cDock failed to move bundles or opee...

Try 9.1

**Comment by dkfiresky** [comment]
Thanks, 9.1.2 worked for me!
