### ISSUE TITLE
cDock multiple versions and crashing

### ISSUE THREAD

**Issue by tonysan2009** [w0lfschild/cDock#18]
Hi there,

I used to have an older cDock version installed on my Mac (the one with the blue app icon) where I created a custom dock for my Mac. I also installed a newer version of cDock (with the current pinkish app icon) at the same time, and my Mac possibly got really confused and no changes apply to the Dock. I restored the original Mavericks Dock from a back up that I had and uninstalled all versions of cDock from my Mac. Then I installed the latest version. At the beginning there was a warning that a BMIL (?) or something like that file already existed and it could possibly make the app not work properly. Unfortunately I didn't write down the directory of the file. Now I open up cDock and get this message as well:
The following line is neither a comment, nor does it contain a valid command:

middle

And it crashes.
Apparently there is a file somewhere from the previous version (which I really loved as I had made a custom dock which I can't import to the newer version) which makes the app crash etc.
Please help? :)

Thank you much in advance and for your excellent support.

All the best,

Anthony

**Comment by w0lfschild** [comment]
Not sure I follow what's going on here? Are you using version 9.3?

I don't know why that error would be showing up. You could post an image of the error with:

Command + Shift + 4 to take a screenshot and post it here, that might help.

**Comment by tonysan2009** [comment]
Hi there,

To be honest I love using version 5.4 under Mavericks (as I have created a replica of Yosemite dock). So I had this version installed (I named in as cDock 1 under the Applications menu). Then I installed vn 6.3.2 I believe under the name cDock 2 to test it. I even upgraded to the latest version (9.3 I believe?). The thing is even I have one of the versions installed they don't work properly individually. For example now that I have only vn 5.4 installed using my pre-made dock works. If I restore to the original and then try again to use my pre-made dock nothing happens. Also, when I have only 9.3 installed it doesn't work properly - for example when I select the fray dock I just have an invisible dock. In both cases of uninstalling I am using Clean my Mac vn2 which despite the app finds some plist files and uninstalls them as well. So I am wondering whether there are some more files that Clean my mac doesn't find?
For example, I found under Library/Application Support/ SIMBL the file "cDock" that possibly caused that problem and I manually deleted it. But still the problems remain. 
Thank you so much again in advance!!
The app is great nevertheless :dancer: 

Cheers,

Anthony

**Comment by tonysan2009** [comment]
Since it the previous message was written in a hurry, I clarify things a bit more (sorry for that):
Hi there,

To be honest I love using version 5.4 under Mavericks (as I have created a replica of a Yosemite dock). So I had this version installed (I named it as cDock 1 under the Applications folder). Then I installed vn 6.3.2 I believe under the name cDock 2 to test it. I even upgraded the 6.3.2 to the latest version (9.3 I believe?). The thing is even I have one of the versions installed at a time, they don't work properly. For example now that I have only vn 5.4 installed, my pre-made dock works. If I restore to the original and then try again to use my pre-made dock again nothing happens and the default Mavericks dock is still on. Also, when I only have vn9.3 installed now, it doesn't work properly - for example when I select the gray dock I just get an invisible dock. In both cases I uninstall using Clean my Mac vn2, which despite the app it finds some additional plist files and uninstalls them as well. So I am wondering whether there are more files that Clean my mac doesn't find?
For example, I found under Library/Application Support/ SIMBL the file "cDock" that possibly caused that problem and I manually deleted it. But still the problems remain. 
Thank you so much again in advance!!
The app is great nevertheless :dancer:

Cheers,

Anthony

**Comment by w0lfschild** [comment]
Well the reason is that Apple broke EasySIMBL with their most recent security update for 10.9 through 10.11 which means nothing below cDock 8.2 will work if your system is up to date.

cDock 8.2 and up use SIMBL which will work
cDock 9.0 and up completely changed the cDockBundle which makes the custom docks and also completely changed the method of making custom docks

What you need to do is remake your custom dock using the 9.0 method or use 8.2
