### ISSUE TITLE
Bottom Corner Radius

### ISSUE THREAD

**Issue by mdazmir** [w0lfschild/cDock#2]
Is it possible to only change the bottom left and bottom right corner radius? Currently the custom setting for the corner radius will change all four corners. Anyway, thanks for the great tool.

**Comment by w0lfschild** [comment]
Nope. If you don't want them to show just move the dock down until they're off-screen (which is how it should look).

**Comment by w0lfschild** [comment]
Well I fixed the bottom corners showing issue so I'm gonna close this.
