### ISSUE TITLE
Dock performance issues

### ISSUE THREAD

**Issue by w0lfschild** [w0lfschild/cDock#20]
I noticed an issue where I get massive CPU usage while moving the mouse over the dock with some options enabled, notably icon reflections and custom indicators.

I've not had anyone else report this despite the Dock taking +50% CPU on my core 2 duo when performing the above action.

Report any theme / performance related issues here.

**Comment by AttracksPilot** [comment]
Yeah, Wolfgang.
I just noticed it while working on my 'own' custom dock. With reflection and custom indicators, I see that moving over the dock is far from smooth.
Cheers

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/cDock/releases/tag/v9.4 Includes fixes for several performance issues.

**Comment by markusbern** [comment]
Had to uninstall. Mac was not responding. Menu bar aplet still not working.

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/cDock/releases/tag/v9.5 fixes all remaining performance issues aside from custom separators on OS X 10.9
