### ISSUE TITLE
"Run Shell Script" encountered an error

### ISSUE THREAD

**Issue by markusbern** [w0lfschild/cDock#21]
![cdock](https://cloud.githubusercontent.com/assets/13661766/9120601/7124f362-3c7d-11e5-9545-6afdf78c582f.png)

I get the constantly the following error message. Uninstall is not working/Helping.

**Comment by markusbern** [comment]
forgot to say it is 9.3.1 and OS X 10.10.4

**Comment by w0lfschild** [comment]
What are you clicking?

**Comment by markusbern** [comment]
on the "ok"

**Comment by w0lfschild** [comment]
... No I mean to get that dialog to show up. What are you doing before that shows up?

**Comment by markusbern** [comment]
nothing, it comes when i start up the mac

**Comment by w0lfschild** [comment]
Well then, sounds like this has nothing to do with the menubar app.

**Comment by markusbern** [comment]
but it appears since the installation of 9.3.1 before the activation of the applet, there was no error or message

**Comment by w0lfschild** [comment]
The launch agent "cDock Agent" is the only thing that starts when you start your mac.

**Comment by markusbern** [comment]
yes, i actually restarted my mac now, and the wheel from "cDock Agent" is spinning, until I click on "ok" on the above mentioned error-message. the wheel is disapearing.

**Comment by markusbern** [comment]
and my mac is working fine.

**Comment by w0lfschild** [comment]
I'm guessing it's this line failing for you, not sure why, I'll look into it.

    osascript -e "tell application \"Finder\" to inject SIMBL into Snow Leopard"

**Comment by markusbern** [comment]
9.4 has not solved the problem. I unstalled the application, the error still appears.

**Comment by w0lfschild** [comment]
Well sounds like it's not related to cDock if it's not even installed.

**Comment by markusbern** [comment]
it is, the wheel is appearing, spinning, then i click on "ok", then the wheel disappears. And this "Icon" is related to cDock. Have you an idea, how the unistall the remains of the applet? I don't like the idea of a clean install of my mac.

**Comment by markusbern** [comment]
Hope it helps:
![fehler](https://cloud.githubusercontent.com/assets/13661766/9149542/d659ee58-3daf-11e5-9d9c-3791d1b091df.png)

**Comment by dkfiresky** [comment]
@markusbern @w0lfschild I actually think it's nothing related to the cDock. It's the Dark Boot project (https://github.com/w0lfschild/DarkBoot) and it's trying to upgrade (as I understood).

**Comment by w0lfschild** [comment]
Indeed. I guess cDock's menu-bar icon does look exactly like Automator script icon. Even still shame on you OP for not even reading, it clearly says **dBoot** which has literally nothing to do with cDock.
