### ISSUE TITLE
Can't apply "custom dock menus"

### ISSUE THREAD

**Issue by phillipar33** [w0lfschild/cDock#22]
I'm not sure if it's normal, but every time I type in my admin password it shows a red arrow next to the password box. I then close the box and everything seems to work (in other words, I can change everything but this one option). Any ideas?

**Comment by w0lfschild** [comment]
Sounds like you're not entering the proper password or your account doesn't have sudo access.

The red arrow indicates that a blank password is not accepted.

I haven't changed anything about that method recently.

**Comment by phillipar33** [comment]
Ah, that makes sense. I had a one-character password. I switched it to one of my longer ones for a moment and that fixed the problem. Thank you! You rock :)
