### ISSUE TITLE
Unable to change dock background

### ISSUE THREAD

**Issue by grcombs** [w0lfschild/cDock#23]
Unable to change the background of the to anything other than the default

**Comment by w0lfschild** [comment]
This post has no useful information.

**Comment by grcombs** [comment]
OK, I either have ver 9.2 or 9.3.1. Can't tell since I see both versions. What I should have said was I'm unable to change the dock theme. No matter which theme I choose, the dock background never changes. Does that help?

**Comment by w0lfschild** [comment]
No sorry that doesn't help. 

You can email me your logs.

you should also read before posting https://github.com/w0lfschild/cDock/issues/16

I'm gonna guess chances are *highly likely* that you're either running 10.11 with SIP on or you've entered the wrong information when prompted by either "cDock-Helper" or a Finder dialog.

**Comment by grcombs** [comment]
That was it. I had SIP on. Once I turned it off, I can now set the dock
theme.

Gary

**Comment by w0lfschild** [comment]
Great, closing this now.
