### ISSUE TITLE
Inconsistent versions

### ISSUE THREAD

**Issue by grcombs** [w0lfschild/cDock#24]
The menubar cDock app reports version 9.1 (build1), but the cDock application reports version 9.3.1. Which is correct??

**Comment by w0lfschild** [comment]
Yup I'll make sure these are aligned in the coming version. Always assume the highest version is the actual one.

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/cDock/releases/tag/v9.4

I've aligned the version numbers.
