### ISSUE TITLE
Theming failing on 10.9.5

### ISSUE THREAD

**Issue by Turbofoehn** [w0lfschild/cDock#25]
Hi, since upgrading from 10.9.4 to 10.9.5 cDock has stopped working for me. When applying a theme, the dock will restart, but retains it's stock theme.
I am using cDock 9.4.1, so it shouldn't be related to #5.

Is it possible to attach log files here or should I email them?

Thanks, Felix

**Comment by w0lfschild** [comment]
Nope you can't attach logs here.

Probably a permissions or password issue on your end.

**Comment by Turbofoehn** [comment]
​logs.zip (https://db.tt/2qElWf7k)​  
It asked for my password after auto updating iirc. Reseting cDock via the extra settings window did not help…


Am Samstag, 8. August 2015 um 01:42 schrieb Wolfgang Baird:

**Comment by w0lfschild** [comment]
You need to enter the correct login when asked. Your logs don't have the helper app logs which means you haven't installed SIMBL which is required.

It should automatically ask you when you open cDock but you can also open the app here:

    /Applications/cDock.app/Contents/Resources/helpers/cDock-Helper.app

**Comment by Turbofoehn** [comment]
Opening cDock does not ask for a password, opening the helper app manually does.  

I had manually removed SIMBL because I suspected it was an old version from before cDock. The logs claim to have installed files, but it still does not work.

New logs:​

logs.zip (https://db.tt/8hD1sBb4)​

Thank you for your help

**Comment by R-S-T** [comment]
Same behavior with me. No theme under 10.10.4...
If there is anything I can try, please let me know!

**Comment by w0lfschild** [comment]
If cDock is not working make sure these 2 files are in place

    /Library/Application Support/SIMBL/Plugins/cDock.bundle
    /System/Library/ScriptingAdditions/SIMBL.osax

You can see if cDock is loading by opening Console and searching for `Dock`. If it has loaded you'll see something like `OS X 10.10, cDock loaded...`

**Comment by R-S-T** [comment]
files are in the correct location.

in console I found this:
10.08.15 10:24:43,296 cDock[2632]: App did finish launching
10.08.15 10:24:43,336 SIMBL Agent[692]: warning: failed to get scripting definition from /Applications/cDock.app; it may not be scriptable.
10.08.15 10:24:43,342 cDock[2632]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/System/Library/ScriptingAdditions/SIMBL.osax"
10.08.15 10:24:48,000 kernel[0]: Sandbox: cDock(2632) System Policy: deny file-write-unlink /Users/RS/Library/Saved Application State/org.w0lf.cDock.savedState/restorecount.plist
10.08.15 10:24:54,408 NotificationCenter[706]: Dock connection interrupted!
10.08.15 10:24:54,409 NotificationCenter[706]: Dock connection invalid!


with 9.4.1 colorful sidebar is not working, but did in 9.4. The option stays unchecked every time I open „extra settings“

**Comment by Turbofoehn** [comment]
> files are in the correct location.

same here

Console:

```
10.08.15 16:57:36,425	cDock[36187]	App did finish launching
10.08.15 16:58:00,456	com.apple.launchd.peruser.501[730]	(com.apple.Dock.agent[800]) Exited: Killed: 9
10.08.15 16:58:01,505	Dock[36716]	Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/System/Library/ScriptingAdditions/SIMBL.osax"
10.08.15 16:58:03,153	Dock[36716]	Warning: Cache image returned by the server has size range covering all valid image sizes. Binding: VariantBinding [0x7e03] flags: 0x10 binding: BundleBinding [0x7d03] URL: file:///Applications/Microsoft%20Office%202011/Office/Microsoft%20Office%20Reminders.app/ bundle identifier: com.microsoft.outlook.officereminders request size:176 scale: 1
10.08.15 16:58:03,473	Dock[36716]	Warning: Cache image returned by the server has size range covering all valid image sizes. Binding: VariantBinding [0xaf03] flags: 0x10 binding: BundleBinding [0xae03] URL: file:///Applications/arRsync.app/ bundle identifier: com.arrsync.arrsync request size:176 scale: 1
10.08.15 16:58:04,432	Dock[36716]	Warning: Cache image returned by the server has size range covering all valid image sizes. Binding: VariantBinding [0x11b03] flags: 0x10 binding: BundleBinding [0x11a03] URL: file:///Applications/Max.app/ bundle identifier: org.sbooth.Max request size:176 scale: 1
10.08.15 16:58:05,312	Dock[36716]	Warning: Cache image returned by the server has size range covering all valid image sizes. Binding: VariantBinding [0x18303] flags: 0x10 binding: BundleBinding [0x18203] URL: file:///Applications/UnRarX.app/ bundle identifier: com.peternoriega.unrarx request size:176 scale: 1
10.08.15 16:58:05,957	Dock[36716]	Warning: Cache image returned by the server has size range covering all valid image sizes. Binding: VariantBinding [0x1bb03] flags: 0x10 binding: BundleBinding [0x1ba03] URL: file:///Applications/Zinio%20Reader%204.app/ bundle identifier: ZinioReader4.9310D8F796442B71068C511E15D70529A702D19D.1 request size:176 scale: 1
10.08.15 16:59:41,385	com.apple.dock.extra[36718]	<NSXPCConnection: 0x7fe811f38350>: received an undecodable message (no exported object to receive message). Dropping message.
 
```

**Comment by w0lfschild** [comment]
Well it looks like SIMBL is open you can try opening terminal and running:

    killall -Kill Dock; sleep 1; osascript -e "tell application \"Dock\" to inject SIMBL into Snow Leopard"

**Comment by R-S-T** [comment]
This is the answer i got. Still not working

osascript: OpenScripting.framework - scripting addition "/Users/RS/Library/ScriptingAdditions/24U Appearance OSAX.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.
27:57: execution error: Dock got an error: Application isn’t running. (-600)

**Comment by w0lfschild** [comment]
Then just run

`osascript -e "tell application \"Dock\" to inject SIMBL into Snow Leopard"`

then move your mouse over the dock.

**Comment by R-S-T** [comment]
did not change anything in the behavior of cdock.
Still no colorful sidebar or themes with 9.4.1

**Comment by w0lfschild** [comment]
Could be a SIMBL issue, I dunno it's hard to say. Could also be stuff not installing because of permissions or something else...

Do yall actually have a 'normal' password could be related to this issue: https://github.com/w0lfschild/cDock/issues/22

**Comment by Turbofoehn** [comment]
> Do yall actually have a 'normal' password could be related to this issue: #22

Yup.

Real strange, never had a problem prior to 10.9.5…

Is there alternative SIMBL versions I could try?

**Comment by R-S-T** [comment]
version 9.5 brought back colorful sidebars. still no themes…

**Comment by w0lfschild** [comment]
What do you get from entering this in terminal?

`defaults read com.apple.dock hide-mirror`

**Comment by R-S-T** [comment]
zero

**Comment by w0lfschild** [comment]
Okay well then that's the problem for whatever reason the bundle is failing to change that.

Enter: `defaults write com.apple.dock hide-mirror -bool TRUE`

cDock should work after that.

**Comment by R-S-T** [comment]
Sorry, still no themes….

**Comment by w0lfschild** [comment]
Did you re-apply using cDock?

**Comment by R-S-T** [comment]
sure

**Comment by allannyholm** [comment]
I'm echoing the situation with no themes on 10.9.5 - I switched back due to the Flavours application but even without it cDock is not injecting itself into the Dock.

**Comment by w0lfschild** [comment]
@allannyholm 

Set this in terminal: `defaults write com.apple.dock hide-mirror -bool TRUE; killall -Kill Dock`

The bundle should do that automatically but I suppose it's not for you.

**Comment by allannyholm** [comment]
Thanks. After a couple of reboots it now works.
