### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by dkfiresky** [w0lfschild/cDock#27]
Milestones is a great github feature: https://guides.github.com/features/issues/#filtering
You might be interested in adding those into your project.

**Comment by w0lfschild** [comment]
Probably will not set up milestones. I'm the only one working on this and there aren't exactly set milestones, I just randomly up the version every once in a while when I feel like I've done something significant.

**Comment by dkfiresky** [comment]
Indeed, it depends on a project size.
There is also good practice of using [semantic versioning](http://semver.org/).

**Comment by w0lfschild** [comment]
I already stick loosely to semantic versioning

large change -- improvements / general fixes -- bugfix
