### ISSUE TITLE
Border alpha value does not applied (v9.4.1)

### ISSUE THREAD

**Issue by dkfiresky** [w0lfschild/cDock#28]
Border alpha value (cd_borderBGA) does not change border transparency.

**Comment by w0lfschild** [comment]
It does but it's not set the same as the others you'd need to enter 0.00 - 1.00 value instead of 0 - 100.

Regardless this will be fixed as it's just a divide by 100 on the value that's needed.

**Comment by w0lfschild** [comment]
Fixed.
