### ISSUE TITLE
In colored sidebar iCloud icon is broken

### ISSUE THREAD

**Issue by Michelasso** [w0lfschild/cDock#31]
It shows as a the icon of a normal file instead of a folder. This months ago when I first installed it and now with the latest release. (9.4.1). See attached img.

![screenshot 2015-08-10 10 56 06](https://cloud.githubusercontent.com/assets/2322927/9164831/9b003eac-3f4e-11e5-8381-26df72497e88.png)

**Comment by w0lfschild** [comment]
Won't be fixed, if you want this functionality check out [XtraFinder](https://www.trankynam.com/xtrafinder/).
