### ISSUE TITLE
cDock agent does not start properly on login

### ISSUE THREAD

**Issue by dkfiresky** [w0lfschild/cDock#32]
cDock agent is added to login items, but it does not apply the theme nor launches correctly.
Following errors found in Console:

```
10.08.15 13:35:56,463 loginwindow[1091]: ERROR | OpenItemAtURL | Login items - LSOpenApplication returned error -10827, url=/Applications/cDock.app/Contents/Resources/helpers/cDock Agent.app

10.08.15 13:35:56,463 loginwindow[1091]: ERROR | LaunchItemsInSharedFileListRef | Unable to lauch startup item: file:///Applications/cDock.app/Contents/Resources/helpers/cDock%20Agent.app/
```

**Comment by dkfiresky** [comment]
But if you run cDock manually, everything works fine: the configured theme is applied, cDock agent (and cDock itself) launches.

**Comment by w0lfschild** [comment]
I would try removing and re-adding the agent.

**Comment by dkfiresky** [comment]
If I remove and add again cDock agent to login items the behaviour is the same.

**Comment by w0lfschild** [comment]
Well I have no idea then. Seems like this issue is with loginwindow.

**Comment by dkfiresky** [comment]
Found new issue in the Console:
```
13.08.15 06:43:21,310 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.domain.pid.cDock Agent.1102) Could not resolve origin of domain. XPC services in this domain's bundle will not be bootstrapped: error = 2: No such file or directory, taint = (untainted)
```

**Comment by w0lfschild** [comment]
Once again. I'm not going to look into this. I don't know why you're computer is trying to open app_mode_loader instead of cDock Agent.

**Comment by rikvsonsbeek** [comment]
Same problem with me on my MacBook Pro. cDock does not start automatically. Just to let you now dkfiresky is not the only one.

**Comment by w0lfschild** [comment]
Well I can't really help you. This problem likely has nothing to do with cDock. If it did I would undoubtedly have more feedback considering the latest version alone has 51,000+ downloads. It's probably an issue with your setup.

All the app does is for the login item is:

    osascript -e "tell application \"System Events\" to delete login items \"cDock Agent\""
    osascript -e "tell application \"System Events\" to make new login item at end of login items with properties {path:\"$cdock_path\", hidden:false}"

You could try manually adding the login item.

**Comment by rikvsonsbeek** [comment]
I found out what the problem is. cDock Agent did not open because the setting was that it was downloaded from a "not-apple" source. Changing this setting in the security of the system preferences did the trick. It works perfectly now! Thanks.

**Comment by dkfiresky** [comment]
@rikvsonsbeek thats why you should not use this software. It's just hacking your mac.
