### ISSUE TITLE
cDock 2 Titlebar

### ISSUE THREAD

**Issue by axialix** [w0lfschild/cDock#38]
I thought DockMod was great, but this app blows it away like a shotgun blast.  Very well done.
I don't have any issues with it and I'm probably not supposed to post this here, but I do have one suggestion - please take it or leave it - about the app title.  I just thought it would look a bit tighter and cool ala the attached pic.  Not saying you should go back and change anything, just perhaps for a future release or whatnot.  Once again, very nice work.

<img width="655" alt="cdock2" src="https://cloud.githubusercontent.com/assets/14351178/10270123/a91ac3b6-6ab6-11e5-8c54-4e4174cb8dd2.png">

**Comment by dkfiresky** [comment]
The titlebar also lags sometimes, it appears as regular titlebar and then switches back to normal.

**Comment by axialix** [comment]
I have not observed that behavior on my machine.  If it were an image instead of text, would this still occur?

**Comment by dkfiresky** [comment]
It was regular mac os x window titlebar, not the titlebar shown on your screenshot.

**Comment by w0lfschild** [comment]
I assume @dkfiresky means this showing briefly when the application first opens:
![screen shot 2015-10-05 at 11 42 04 am](https://cloud.githubusercontent.com/assets/1920148/10289982/4f7fd436-6b56-11e5-94bb-243ebcad5559.png)

That will be fixed in the future by moving setup stuff from applicationDidFinishLaunching to applicationWillFinishLaunching.

**Comment by axialix** [comment]
I have a question on a different topic.  Is there any way to make a fullscreen dock but have a background image?  Currently fullscreen only has colors.

**Comment by w0lfschild** [comment]
@axialix Set it to fullscreen? I'm not sure what you're asking.

![screen shot 2015-10-05 at 2 01 34 pm](https://cloud.githubusercontent.com/assets/1920148/10293527/bc65a37e-6b69-11e5-9dc9-2ee245c59dc7.png)

**Comment by dkfiresky** [comment]
@w0lfschild Yes, thats what i'm talking about.

**Comment by axialix** [comment]
My apologies...I didn't realize I had to uncheck the "Dock background image is 3D" option to have a full width dock.  Works perfectly now.  Thanks very much.

**Comment by axialix** [comment]
One other thing though, how about a setting to remember the position on screen that cDock2 opens at?  Currently it just opens somewhere on the lower left of my screen, which is inconveniently not where I like it.  Kinda like the TextEdit.app which always opens on the bottom of my screen.  Any chance of this happening?

**Comment by w0lfschild** [comment]
@axialix Yes that can be done.

**Comment by w0lfschild** [comment]
cDock should now remember last window location and not show the default titlebar on launch.

**Comment by axialix** [comment]
Excellent.  Thank you very much!

**Comment by dkfiresky** [comment]
@axialix Maybe this issue can be closed?

**Comment by axialix** [comment]
Yes, app now remembers last opened location.

**Comment by dkfiresky** [comment]
@axialix you can press the `Close Issue` button then.

**Comment by axialix** [comment]
Done.
