### ISSUE TITLE
cDock 2 on El Capitan doesn't work (cDock 1 does)

### ISSUE THREAD

**Issue by Mathek** [w0lfschild/cDock#39]
Hello,

I have an iMac which is running great with cDock 1 & 2 and I have a Macbook Air (late 2012) which is running great with cDock 1 but not with cDock 2.

Both have El Capitan installed.

I disabled SIP and installed cDock 1. cDock 1 worked great.
After this I made an update to cDock 2. But cDock 2 didn't worked anymore. 

Do you have any suggestions how to fix this?

**Comment by dkfiresky** [comment]
@Mathek Try to uninstall cDock 1 and clean install cDock 2

**Comment by Mathek** [comment]
Hello dkfiresky,
thank you for your Answer.
I deleted cDock with an AppCleaner and restarted OS X.
After the restart I copied the cDock 2 App into my Programms Folder bur cDock 2 is still not working.
Are there any logs which I could send you? 

I guess a clean install of OS X would be sufficient to solve the problem, since cDock 2 is working on my other mac. But I would like to avoid this.

**Comment by dkfiresky** [comment]
@Mathek maybe @w0lfschild can help you.

**Comment by w0lfschild** [comment]
Could be related to this issue https://github.com/w0lfschild/cDock2/issues/2

**Comment by w0lfschild** [comment]
Try 0.9.8
