### ISSUE TITLE
Hide menu bar icon

### ISSUE THREAD

**Issue by MikeBeas** [w0lfschild/cDock#4]
I don't like having a cluttered menu bar and prefer to disable or hide as many icons up there as I can. The Refresh Dock app doesn't let me hide the icon (at least not that I can see). Please add a way to hide the icon.

**Comment by w0lfschild** [comment]
You can just quit the menubar app.

**Comment by w0lfschild** [comment]
The next version will have an option to not auto launch the menu bar applet.
