### ISSUE TITLE
"Autohide speed" slider makes it hard to set default speed

### ISSUE THREAD

**Issue by MikeBeas** [w0lfschild/cDock#40]
The new GUI in version 2.0 is a great update, but the slider for changing the autohide speed makes it difficult to reset that option to its default value. In the old interface this was the "medium" setting, but here it's next to impossible to restore.

Unfortunately the slider also resets to the slowest possible setting between app launches, meaning if you hit that "apply" button without moving it, you lose your choice and have to set the value back to where you had it, which, again, is very hard with a slider instead of something like a stepper or a dropdown.

**Comment by w0lfschild** [comment]
Agreed, the dock settings sliders need to be changed.

**Comment by w0lfschild** [comment]
![screen shot 2015-12-22 at 10 34 14 pm](https://cloud.githubusercontent.com/assets/1920148/11972108/41f52666-a8fc-11e5-9242-513afc2bfb71.png)
