### ISSUE TITLE
cDock prompts to download 2.0 on every reboot

### ISSUE THREAD

**Issue by MikeBeas** [w0lfschild/cDock#42]
Every time I reboot my Mac, cDock's update window pops up and asks me to install version 2.0. I have already done so twice, but it keeps prompting me for some reason.

**Comment by w0lfschild** [comment]
I feel like this should be fixed with 0.9.8

**Comment by dkfiresky** [comment]
@MikeBeas can you check the issue again please?

**Comment by MikeBeas** [comment]
Appears to be resolved.

**Comment by dkfiresky** [comment]
@MikeBeas There is `Close Issue` button, you might want to press it.
