### ISSUE TITLE
cDock 2  (0.9.7 / OS X 10.11)

### ISSUE THREAD

**Issue by rlpoland** [w0lfschild/cDock#43]
Fails on my iMac, works on my MBP.
Robert Poland
iMac, Late 2013, 14,2
  3.2 GHz Intel Core I5, 27” 
  16 GB Ram, 1TB Fusion HD
  OS X 10.11
MacBook Pro 15" Early 2008, 4,1
  2.4 GHz Intel Core 2 Duo
  6 GB Ram
  OWC 3G SSD 240GB 
  OS X 10.11
![screen shot 2015-10-09 at 9 38 39 am](https://cloud.githubusercontent.com/assets/15052646/10398771/18f42728-6e6c-11e5-9e1f-6b4307253e06.png)

**Comment by w0lfschild** [comment]
Sadly random info about your computer specs doesn't help me in any way.

I'm just gonna assume the issue is with the bundle. Should be at /Library/Application Support/SIMBL/Plugins/cDock.bundle and should be version 0.10.1911.

Check if 0.9.8 works for you.

**Comment by rlpoland** [comment]
> On Oct 10, 2015, at 9:54:PM, Wolfgang Baird <notifications@github.com> wrote:
> 
> Sadly random info about your computer specs doesn't help me in any way.
> 
> I'm just gonna assume the issue is with the bundle. Should be at /Library/Application Support/SIMBL/Plugins/cDock.bundle and should be version 0.10.1911.
> 
> Check if 0.9.8 works for you.
> 
> —
> Reply to this email directly or view it on GitHub.

Found the problem. When I updated to version 0,9,7 the the cDock bundle was removed from the Plugins folder. Adding it back in fixes it.

I updated to version 0.9.8 and cDock still works even though the cDock bundle is still at version 0.10.1904.

Robert Poland
iMac, Late 2013, 14,2
  3.2 GHz Intel Core I5, 27” 
  16 GB Ram, 1TB Fusion HD
  OS X 10.11

**Comment by rlpoland** [comment]
Wolfgang,

After much effort I find that enabling cDock (SIP, etc.) with High Sierra messes up much of High Sierra.

I've had to reinstall High Sierra 3 times so far.

Will there ever be an update to cDock?

> On Oct 24, 2015, at 2:24:PM, Wolfgang Baird <notifications@github.com> wrote:
> 
> Closed #43 <https://github.com/w0lfschild/cDock/issues/43>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/w0lfschild/cDock/issues/43#event-444645066>.
> 

Robert Poland
Fort Collins, CO
