### ISSUE TITLE
cDock 2 no themes running 10.10.5

### ISSUE THREAD

**Issue by R-S-T** [w0lfschild/cDock#44]
cdock 2 made no difference. still no themes showing for me.
You just closed the old issue #25, so I open a new one for cdock 2

**Comment by w0lfschild** [comment]
Sounds like an issue I'm not gonna fix. I'm guessing you've got permissions issue with creating/editing plists or something.

I have no idea what your issue is by cDock and cDock 2 both work on 10.9.5

**Comment by w0lfschild** [comment]
Gonna refer over to here: https://github.com/w0lfschild/cDock2/issues/2
