### ISSUE TITLE
cDock 9.5 crash

### ISSUE THREAD

**Issue by 9jkh** [w0lfschild/cDock#45]
Any idea what's going on here, and what to do to fix this?

```
10/14/15 11:45:57.760 AM Dock[328]: *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <CALayerArray: 0x7f9638e23500> was mutated while being enumerated.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010bdf125c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000010ae95e75 objc_exception_throw + 43
	2   CoreFoundation                      0x000000010bdf0b64 __NSFastEnumerationMutationHandler + 164
	3   cDock                               0x0000000113d84f1e ___loadShadows_block_invoke_2 + 382
	4   libdispatch.dylib                   0x000000010c2221bb _dispatch_call_block_and_release + 12
	5   libdispatch.dylib                   0x000000010c21f28d _dispatch_client_callout + 8
	6   libdispatch.dylib                   0x000000010c227433 _dispatch_after_timer_callback + 77
	7   libdispatch.dylib                   0x000000010c21f28d _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x000000010c221885 _dispatch_source_invoke + 413
	9   libdispatch.dylib                   0x000000010c226e97 _dispatch_main_queue_callback_4CF + 244
	10  CoreFoundation                      0x000000010bd584f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	11  CoreFoundation                      0x000000010bd13714 __CFRunLoopRun + 1636
	12  CoreFoundation                      0x000000010bd12e75 CFRunLoopRunSpecific + 309
	13  Dock                                0x0000000108de7063 Dock + 20579
	14  libdyld.dylib                       0x000000010c25b5fd start + 1
)
```

**Comment by w0lfschild** [comment]
Try using the latest version of cDock.

**Comment by 9jkh** [comment]
Crashes stopped for a while with new version, but resumed recently. Happens after login and just after cDock opens to make changes to the default Dock. Two new crashes, both identical. Can't attach file. Here's what's most important.

Process:         Dock [315]
Path:            /System/Library/CoreServices/Dock.app/Contents/MacOS/Dock
Identifier:      com.apple.dock
Version:         1.8 (1314.12)
Build Info:      Dock-1314012000000000~1
Code Type:       X86-64 (Native)
Parent Process:  launchd [261]
Responsible:     Dock [315]
User ID:         502

Date/Time:       2015-12-18 12:38:53.924 -0500
OS Version:      Mac OS X 10.9.5 (13F1507)
Report Version:  11
Anonymous UUID:  B7D85D4A-FEE7-4290-F6E3-9C34461FD69B


Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <CALayerArray: 0x7f98f2d91460> was mutated while being enumerated.'
abort() called
terminating with uncaught exception of type NSException

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff956ae25c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x00007fff8cdeae75 objc_exception_throw + 43
2   CoreFoundation                      0x00007fff956adb64 __NSFastEnumerationMutationHandler + 164
3   cDock                               0x000000010d3bbf1e ___loadShadows_block_invoke_2 + 382
4   libdispatch.dylib                   0x00007fff8f5091bb _dispatch_call_block_and_release + 12
5   libdispatch.dylib                   0x00007fff8f50628d _dispatch_client_callout + 8
6   libdispatch.dylib                   0x00007fff8f50e433 _dispatch_after_timer_callback + 77
7   libdispatch.dylib                   0x00007fff8f50628d _dispatch_client_callout + 8
8   libdispatch.dylib                   0x00007fff8f508885 _dispatch_source_invoke + 413
9   libdispatch.dylib                   0x00007fff8f50de97 _dispatch_main_queue_callback_4CF + 244
10  CoreFoundation                      0x00007fff956154f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
11  CoreFoundation                      0x00007fff955d0714 __CFRunLoopRun + 1636
12  CoreFoundation                      0x00007fff955cfe75 CFRunLoopRunSpecific + 309
13  Dock                                0x0000000108337063 Dock + 20579
14  libdyld.dylib                       0x00007fff8f0b05fd start + 1

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8df74866 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff9798735c pthread_kill + 92
2   libsystem_c.dylib             	0x00007fff974a9b2e abort + 125
3   libc++abi.dylib               	0x00007fff97cdff31 abort_message + 257
4   libc++abi.dylib               	0x00007fff97d05952 default_terminate_handler() + 264
5   libobjc.A.dylib               	0x00007fff8cdeb30d _objc_terminate() + 103
6   libc++abi.dylib               	0x00007fff97d031d1 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff97d03246 std::terminate() + 54
8   libobjc.A.dylib               	0x00007fff8cdeb0b0 objc_terminate + 9
9   libdispatch.dylib             	0x00007fff8f5062a1 _dispatch_client_callout + 28
10  libdispatch.dylib             	0x00007fff8f50e433 _dispatch_after_timer_callback + 77
11  libdispatch.dylib             	0x00007fff8f50628d _dispatch_client_callout + 8
12  libdispatch.dylib             	0x00007fff8f508885 _dispatch_source_invoke + 413
13  libdispatch.dylib             	0x00007fff8f50de97 _dispatch_main_queue_callback_4CF + 244
14  com.apple.CoreFoundation      	0x00007fff956154f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
15  com.apple.CoreFoundation      	0x00007fff955d0714 __CFRunLoopRun + 1636
16  com.apple.CoreFoundation      	0x00007fff955cfe75 CFRunLoopRunSpecific + 309
17  com.apple.dock                	0x0000000108337063 0x108332000 + 20579
18  libdyld.dylib                 	0x00007fff8f0b05fd start + 1
