### ISSUE TITLE
Code at the bottom of Release 8.3 page will completely break the dock.

### ISSUE THREAD

**Issue by CrumbyBread** [w0lfschild/cDock#46]
After typing in the code to revert the changes, I suddenly have my dock removed. I decide to log out and log in and my desktop is black, no mission control or launchpad and most of all, no dock. I soon found out the cause of this and it was simply renaming Dock.app to Dock_trash.app. The soloution is to change it back, sudo mv Dock_trash.app/ Dock.app

**Comment by dkfiresky** [comment]
@CrumbyBread maybe you should use latest version of cDock 2?
