### ISSUE TITLE
cDock Stopped working

### ISSUE THREAD

**Issue by griffwing** [w0lfschild/cDock#5]
just updated to OS X 10.9.5 (13F1096) and cDock stopped working. Keep up the great work!

**Comment by w0lfschild** [comment]
Try this out until I get an update out. I believe EasySIMBL is dead https://github.com/norio-nomura/EasySIMBL which is what I was using to apply the cDock bundles.

http://w0lfschild.github.io/pages/cdock_workaround.html

**Comment by griffwing** [comment]
Great thanks! I'll give it a try!

**Comment by skepticus** [comment]
I tried the workaround for 10.10.4, but when I try to run the script, I get an error. "Expected end of line but found “into”." I guess it's wait time....

**Comment by griffwing** [comment]
Ok I got up to adding saved script to Login Items. Not sure where that is?

**Comment by cmotdibbler** [comment]
Login items are System Prefs/Users and groups hit the button next to password. Then hit the "+" sign to add the saved script. This way the script will load (but not run) when you login/reboot. You'll see a page with script open, select "run" and the cdock will start. You can close the script afterward (I like it tidy) but needs to be done after every boot/login. I'm no scripting guru but this is a passable workaround.

**Comment by griffwing** [comment]
Thanks. Since this isn't a permanent fix I'll just hold off until an update. Thanks for the help!

**Comment by w0lfschild** [comment]
Well lets see if this fixed in [8.0](https://github.com/w0lfschild/cDock/releases/tag/v8.0) 🙏

**Comment by griffwing** [comment]
That's a big negative on it being fixed :-/
