### ISSUE TITLE
Separator doesn't apply with separator.png inside theme folder.

### ISSUE THREAD

**Issue by Sokol90** [w0lfschild/cDock#53]
Hi,

first of all, thanks a lot for your work! It's amazing! :)) 
I run the latest Mavericks version and installed cdock 9.3.1 with a Lion dock theme downloaded from mac rumors forum. I added a separator.png file (classic separator). All run ok but separator doesn't change and remain as default. I make a lot of google search and can't find any solution. What can be wrong? 
I also tried to drag separator file inside other default themes but it didn't work at all and remain the default separator.

Thanks!

**Comment by dkfiresky** [comment]
Theme API changed, so you should define colors for separator, not the image.

**Comment by w0lfschild** [comment]
Yeah I think I removed the option to make a custom indicator because I wasn't able to really get it working nicely and have consistency across OSX versions.

Could come back in the future though. If it really matters you could probably use an older version of cDock (not sure which version).
