### ISSUE TITLE
Theming Window Blank

### ISSUE THREAD

**Issue by suissdc** [w0lfschild/cDock#54]
Just downloaded cDock 2.  Want to activate 3D effect, but theming window is blank.

**Comment by w0lfschild** [comment]
Hmm I should probably have some better exception handling.

What version of cDock2 and what version of OSX?

**Comment by suissdc** [comment]
cDock version is 0.9.8 (Build 1292).  OSX El Capitan 10.11.2

**Comment by w0lfschild** [comment]
Do you get any error in console when searching for cDock?

**Comment by suissdc** [comment]
No.  But I was also having trouble when I booted up with having to enter a password so cDock could make changes.  I always had to enter the password 4 times before it would leave me alone.  I finally just deleted cDock from my computer.  In an older version of OSX I enjoyed the 3D look of the dock, but I am getting used to the 2D look now so I probably won’t worry about trying to reinstall it.

**Comment by w0lfschild** [comment]
I'm guessing you don't have SIMBL installed.

**Comment by suissdc** [comment]
You are probably right since I have no idea what you are talking about.

**Comment by w0lfschild** [comment]
The helper that makes cDock work. If it's not installed the themes tab is supposed to show instructions on how to disable System Integrity Protection or an install button.

**Comment by w0lfschild** [comment]
Still blank with 0.10.1 ?

**Comment by suissdc** [comment]
I uninstalled it because of the repeated login messages I got on bootup.  I’m doing ok without it.
