### ISSUE TITLE
cDock and Mission Control

### ISSUE THREAD

**Issue by kenm22** [w0lfschild/cDock#57]
In 10.11.2 cDock breaks Mission Control. It fails to function.

**Comment by w0lfschild** [comment]
What exactly "breaks", works fine for me.

**Comment by kenm22** [comment]
It does nothing at all with cDock active.

Ken

**Comment by dkfiresky** [comment]
@kenm22 i've got 10.11.2 and cDock and Mission Control works fine. Can you describe exactly what is your problem?

**Comment by kenm22** [comment]
If cDock is enabled and I try to launch Mission Control nothing at all happens. If I disable cDock, Mission Control functions properly.

Since you seem to be having no problem with it I will check further to see if it’s a combination of cDock and something else I have running. Where’s Conflict Catcher when I need it?

Thanks, and Happy Holidays.

Ken

**Comment by w0lfschild** [comment]
What version of cDock are you using?

Are you getting a crash or is mission control just not coming up?

**Comment by kenm22** [comment]
I’m using cDock version 0.9.8 on Mac OS 10.11.2. When I try to launch Mission Control it’s dead…nothing happens. 

Perhaps I have a conflict with a third piece of software as well. I’ll play with it to see what I come up with. Too bad Conflict Catcher isn’t around.

I’ve attached three screen shots of my settings.

Happy Holidays.

Ken

**Comment by dkfiresky** [comment]
@kenm22 there are no screenshots attached.

**Comment by kenm22** [comment]
Let’s try again. I’ve zipped them in a folder.

Ken

**Comment by dkfiresky** [comment]
@kenm22 https://github.com/w0lfschild/cDock/issues/57#issuecomment-167179362
You did not sent anything.

**Comment by kenm22** [comment]
I’ve sent them twice as attachments. The first time I sent three JPEGs, the second time I sent a zipped file containing the attachments.

Just to see if they were sending properly I sent them to myself. They showed up as attachments. I will send them to you from my AOL account. Let’s see if that works.

Ken

**Comment by kenm22** [comment]
See if this works.

Ken






On Dec 24, 2015, at 5:04 PM, Dmitry Kholodilin <notifications@github.com <mailto:notifications@github.com>> wrote:

@kenm22 <https://github.com/kenm22> there are no screenshots attached.

**Comment by w0lfschild** [comment]
You can't attach files to a thread via email, only the web.

**Comment by kenm22** [comment]
Here is the attachment;
[Screen Shots.zip](https://github.com/w0lfschild/cDock/files/73676/Screen.Shots.zip)

**Comment by kenm22** [comment]
Oops. One of the screen shots was closing my MS account. Here it is again.
[Screen Shots.zip](https://github.com/w0lfschild/cDock/files/73678/Screen.Shots.zip)

**Comment by kenm22** [comment]
I've been tinkering with this. I finally trashed my dock preference file and rebuilt the dock. Mission Control works fine now. Apparently I had a corrupted dock preference file. 

Thank you all for the help.

Ken
