### ISSUE TITLE
my  MBPR shutdown very slowly with cDock2

### ISSUE THREAD

**Issue by fangxiang1978** [w0lfschild/cDock#58]
OS X: 10.11.2 , When open cDock2,shutdown very very slowly.

**Comment by w0lfschild** [comment]
Probably something SIMBL related. I don't experience this, are you sure it's cDock and not something else?

What specifically is making you think it's cDock? 

Are there errors relating to the dock in console?

**Comment by w0lfschild** [comment]
I'm going to close this since I'm seeing no evidence that this issue is specifically related to cDock.
