### ISSUE TITLE
 Bugs on OS X 10.9.5

### ISSUE THREAD

**Issue by 9jkh** [w0lfschild/cDock#59]
As discussed in https://github.com/w0lfschild/cDock/issues/56, indicator lights in the 9.11 appear as barely visible pinpoints. The resizing controls do not change the size of the lights, only their position, left and right, up or down, next to the application icon. Screenshot below of how I would like to see the indicator lights. Or at least have the resizing option working to enable larger dots, which are now only very tiny pinpoints, and just too small to be noticeable.

![screen shot 2016-01-18 at 11 16 17 pm](https://cloud.githubusercontent.com/assets/10210828/12409661/2d0bbece-be3a-11e5-823a-efc26a4aab85.png)

**Comment by dkfiresky** [comment]
@9jkh there are `Resize standard indicators`, `Indicator width` & `Indicator height` options available, do they fit your request?

![screen shot 2016-01-19 at 8 22 35 pm](https://cloud.githubusercontent.com/assets/2175645/12427973/c30e31ee-beea-11e5-9344-a9cfe0394343.png)

**Comment by 9jkh** [comment]
As I already said in the crash thread, all that does is move the position of the very tiny dot around. It doesn't make it any bigger. Not sure why, since it's supposed to be a "resize" option, but it's not working to resize anything for me.

**Comment by dkfiresky** [comment]
@9jkh You should probably rename this issue (or close this and create new), because it sounds not like the feature request, but an issue with those resizing controls.

**Comment by 9jkh** [comment]
As this issue may be related to having installed cDock from a standard account, I would like to completely uninstall cDock and reinstall from the same account, but with admin privileges. I tried this once, using EasyFind and FindAnyFile (as root), to locate and remove all related cDock items, but, and not sure why, doing so, didn't work properly to do a complete uninstall. 

What is the procedure to uninstall?

**Comment by 9jkh** [comment]
Update: gave my account admin privileges. First, killed cDock.agent, then restarted the application: didn't help. Next, completely and successfully uninstalled every bit and piece of cDock 9.11. Reinstalled the 9.11. Tried every possible combination of themes and settings: the resize option is still not working.

And, besides all this, new crash https://github.com/w0lfschild/cDock/issues/60

**Comment by dkfiresky** [comment]
@9jkh
> What is the proper procedure to uninstall?

Removing following files
 - `/Applications/cDock2.app`
 - `/Library/Application Support/SIMBL/Plugins/cDock.bundle`

should uninstall the cDock from your mac.

**Comment by 9jkh** [comment]
See my update post, after asking how to uninstall. Completely uninstalled and reinstalled. Nothing changed, nothing worked.

**Comment by 9jkh** [comment]
No hope for this?

**Comment by w0lfschild** [comment]
I think I just need to revisit cDocks 10.9 functionality again (sometime soon).

I dunno if it is or is not working tbh although I think it should be?

**Comment by dkfiresky** [comment]
@9jkh should simply upgrade to the latest OS X version which will simply solve all his problems.

**Comment by 9jkh** [comment]
@dkfiresky Re. upgrading to 10.11, I don't mean to be overly rude, but that is a less than useless suggestion. I have zero intention of upgrading to El Cap. And by the way, I have tried doing this with the 9.8, which, I would assume was developed with 10.9 in mind, not just the latest 9.11, and it doesn't work as designed there, as well. Besides that, why shouldn't the 9.11 work with 10.9? Besides the fact that the 9.11 works for resizing with 10.11 on your system, with your configuration (as sample of exactly one user) what evidence do you have for making this assumption? Please if that's all you have to offer, I would prefer it if you would leave the matter to the developer, w0lfschild, himself. 

Maybe I should just revert completely to the 9.7? I only updated to the 9.11 because it was felt that the earlier version, with the earlier cDock.bundle was responsible for the crashes. And, now, as you can see in issue #60, there was at least one crash, even with the 9.11 and the new cDock.bundle (2012.)

@w0lfschild, I would be very grateful indeed if you can get around to seeing if the 9.11 is working properly with 10.9.5 (if you still have that to boot to) for resizing the indicator lights. And perhaps you can also take a look at issue #60, where, in addition to the usual crash log, I have posted logs re. cDock, which might include a clue as to what's going on here.

Many thanks for your continuing help with this.

**Comment by dkfiresky** [comment]
@9jkh you got wrong assumptions with cDock version matching & OS X version. You also got zero contribution statistics, your activity is related only to reporting cDock issues. You also can't make assumptions on what I'm competent in.

You reported 5 issues related to one problem, called "crashes". Each issue appeared after a new OS X 10.9.5 patch being released.

You got replies from @w0lfschild:

https://github.com/w0lfschild/cDock/issues/45#issuecomment-150847631
> Try using the latest version of cDock.

https://github.com/w0lfschild/cDock/issues/56#issuecomment-172397459
> And yes the crashes were likely from using an old version.

And you're still reporting issues related to the crashes.

Reference: https://github.com/w0lfschild/cDock/issues/61

**Comment by 9jkh** [comment]
>>Each issue appeared after a new OS X 10.9.5 patch being released. 
 What kind of "patch?" How do you happen to know what I've patched or not? And, besides, so what?
>>And you're still reporting issues related to the crashes.
So what? 
>>You also can't make assumptions on what I'm competent in.
"Contribution statistics." I don't know what your role is supposed to be here. I suppose anyone who registers and logs in can offer "advice." Regardless, what you happen to think of your competency with cDock, I prefer to get my advice directly from the developer, which you are not.

Thank you for all your "help," but I would be grateful if you would stop posting to this thread.

**Comment by dkfiresky** [comment]
@9jkh no problems, I will stop. Good luck, @w0lfschild.

**Comment by w0lfschild** [comment]
0.9.12 will fix some 10.9.5 issues.

![screen shot 2016-01-23 at 7 24 20 pm](https://cloud.githubusercontent.com/assets/1920148/12534303/f33d5740-c206-11e5-9ccc-87f3b904e689.png)

**Comment by 9jkh** [comment]
Thanks for taking care of this, but I am unable to find the 0.9.12 anywhere, and the automatically install option is still showing the latest as 0.9.11.

**Comment by w0lfschild** [comment]
Yes it is planned, not available now. Soon I hope maybe this weekend.

**Comment by 9jkh** [comment]
Thanks, that is good news.

**Comment by w0lfschild** [comment]
0.10.1 is out and should fix some 10.9 issues

**Comment by 9jkh** [comment]
Installed and so far working great. Thanks for all the work you put into this. Btw, I used the PayPal button.

**Comment by 9jkh** [comment]
One small problem, maybe a bug, not sure. Even though I have the 0.10.1, whenever I log in to my 10.9 I'm told I have the 0.10.0 and get nagged to update to the 10.0.1. Besides that, I have never check for updates set.

**Comment by w0lfschild** [comment]
Should be fixed with 0.10.2

**Comment by 9jkh** [comment]
Thanks, that fixed it.

One other thing, maybe it's somewhere else, and I just don't know about it, but the link for latest release https://github.com/w0lfschild/cDock/releases shows the 0.9.7, and one only discovers that that is far from being the latest release when one opens the Preferences or About tab, depending on which version is currently in use.

As is, it's very confusing. Wouldn't it make sense to keep that latest release page updated with the actual latest release and plus a download link?

![Uploading Screen Shot 2016-02-07 at 10.54.06 AM.png…]()

**Comment by 9jkh** [comment]
Closed in error. Still would like a reply.

**Comment by w0lfschild** [comment]
Because the cDock updater uses the most recent release as it's update target and updating to versions of cDock2 that are now going to be using sparkle instead of my own updater would not work. I will bump it up to 0.10.3 as that's going to be the transition version from home-made updater to sparkle. Also the most recent release of cDock is still 9.5 but that will no longer be updated just cDock2.

**Comment by 9jkh** [comment]
Heard about this?
http://arstechnica.com/security/2016/02/huge-number-of-mac-apps-vulnerable-to-hijacking-and-a-fix-is-elusive/

**Comment by w0lfschild** [comment]
@9jkh see https://github.com/w0lfschild/cDock/issues/64
