### ISSUE TITLE
Mavericks 10.9.5 (13F1096)

### ISSUE THREAD

**Issue by w0lfschild** [w0lfschild/cDock#6]
Please post here of cDock is not working for you on 10.9.5 (13F1096).

**Comment by Mv826** [comment]
cDock is not working on 10.9.5 (13F1096)

The script doesn't run/ go through for the work around; which I can no longer find the link too

SIMBL is installed and the colored finder side bar works, just the dock won't work with cDock

**Comment by fturcheti** [comment]
It's not working here too. 
OS X 10.9.5 (13F1096)

```
3/7/15 12:20:21,463 SIMBL Agent[87705]: warning: failed to get scripting definition from /System/Library/CoreServices/Dock.app; it may not be scriptable.
3/7/15 12:20:21,472 Dock[86977]: AppleEvents/sandbox: Returning errAEPrivilegeError/-10004 and denying dispatch of event ESIM/load from process 'SIMBL Agent'/0x0-0x55e55e, pid=87705, because it is not entitled to send an AppleEvent to this process.
```

**Comment by w0lfschild** [comment]
@fturcheti So it looks like the bundle isn't being injected into the dock.

How about you try this and report back: https://github.com/norio-nomura/EasySIMBL/issues/26#issuecomment-117028426

**Comment by Mv826** [comment]
@w0lfschild I have not done norio-nomura/EasySIMBL#26 (comment)


but heres what my console shows me
![screen shot 2015-07-03 at 7 00 58 pm](https://cloud.githubusercontent.com/assets/13159207/8505512/fdb30e5a-21b5-11e5-9fa7-d48a6fc8e71d.png)

**Comment by MacProDeveloper326** [comment]
I can confirm build 13F1096 does break the main functionality of the application (replacing the dock background). Tooltips can still be hidden.
![screen shot 2015-07-03 at 7 29 42 pm](https://cloud.githubusercontent.com/assets/11094915/8505628/f5f8b490-21b9-11e5-9c99-044bdaa542d3.png)

**Comment by hisako87** [comment]
Echoing what MacProDeveloper326 has stated. Coloured sidebar works though. Sorry I don't know how to do what Nomura listed... I think if I knew where to download the .pkg file, I could test it.

**Comment by w0lfschild** [comment]
Actually based on an email I got from someone who seems to have cDock working on 10.9.5 could someone try this in terminal:

    defaults write com.apple.dock hide-mirror -bool false;killall Dock

**Comment by Mv826** [comment]
Wow that does it alright!! Thank you so much! Now i can resume my studies in peace with my custom dock

**Comment by Mv826** [comment]
The only issue here now is that you have to enter the command manually after applying your settings and i assume after restarting the computer, let me see

**Comment by MacProDeveloper326** [comment]
Negative on that. The commands do not seem to have an effect on the Dock in my case.

**Comment by asoksevil** [comment]
It doesn´t work for me either....

**Comment by imdamfino** [comment]
It didn't work at first for me. I did it a few times, running cdock, quitting the cdock refresh in the menu bar, and in-between each using the terminal command above. Some combination triggered it, and it worked.

**Comment by YBAR** [comment]
Your com.apple.dock fix worked for me on OS X 10.9.5 (13F1096).
Thank you for once again allowing me to hide the unpleasant grey dock tray!
Inspired by previous poster, I also made a donation.
Yaakov

**Comment by asoksevil** [comment]
@imdamfino I´m trying but it just won´t work...

I guess I´ll wait until an official or easier to apply fix shows up.

Thanks for the help!

**Comment by w0lfschild** [comment]
Yup **hide-mirror** was definitely at least part of the issue.

![screen shot 2015-07-04 at 8 23 46 pm](https://cloud.githubusercontent.com/assets/1920148/8510189/9ba778ba-228a-11e5-87af-8ff32a9974d2.png)

**Comment by griffwing** [comment]
Terminal fix seemed to have worked so far. :)

**Comment by asoksevil** [comment]
I finally got it working.. that terminal command line works only if you have cDock 8.1 which I didn´t (I was on 7.4 and you aren´t prompt to automatically update)

In order to fix it you need to:
1. Install/Update cDock 8.1
2. Apply the "transparent theme"
3. Apply the terminal fix

**Comment by hisako87** [comment]
Thank you, that worked for me. With cDock 8.1 I applied the dark dock to the bottom (I don't use sidebar docks), copied/pasted the terminal command, and it works. :) I've no idea if it needs to be reapplied after restarting the computer though.

**Comment by Mv826** [comment]
After you install cDock 8.1 and then SIMBL, you apply the dock theme, run the command (defaults write com.apple.dock hide-mirror -bool false;killall Dock) and it should work. I have restarted I think twice now and the dock stays. I would just keep the code handy if you are going to be changing the dock theme often as you might need to apply the code when changing the theme

On another note, I have manually changed my dock indicator lights, if anyone is interested in that, look into it, it gives the dock a better look
![screen shot 2015-07-05 at 10 24 58 am](https://cloud.githubusercontent.com/assets/13159207/8512030/21d83e18-2300-11e5-97c8-02a37494e081.png)

**Comment by w0lfschild** [comment]
Installed 10.9.5 and did some testing.

Should be fixed with 8.2 as well as a handful of other issues. 👍🏻

**Comment by griffwing** [comment]
works flawlessly! Went thru and tested all the themes and they're working fine! Thank you!!

**Comment by Mv826** [comment]
Thank you!

**Comment by Screenfeed** [comment]
10.9.5 + 8.2 + reboot, still not working :/
>osascript: Performance: Please update this scripting addition to supply a value for TheadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"

**Comment by w0lfschild** [comment]
@Screenfeed Dunno exactly why but I think moving the cDock bundle

    /Applications/cDock.app/Contents/Resources/bundles/cDock.bundle
to

    /Library/Application Support/SIMBL/Plugins

Should make it work, if not reinstall SIMBL.

**Comment by Screenfeed** [comment]
@w0lfschild Thanks for the help. I installed Yosemite this weekend, so, problem solved.

**Comment by TiddK** [comment]
I've used cDock to 'flatten' my Dock in Mavericks. That part has worked fine. But I cannot get the 'open app indicators' to show under the relevant icons no matter what settings I try. If I change a setting, the indicators flash on very briefly then disappear again. What am I doing wrong?

**Comment by TiddK** [comment]
(Solved).
