### ISSUE TITLE
Can't get to disable rootless to instal SIMBL of cDock

### ISSUE THREAD

**Issue by florcortese** [w0lfschild/cDock#63]
When I use the CMD - R on restart I get a window with several options including Disk Utility but I do not get the terminal.  I was eventually able to open terminal and type in the recommended "cartel disable" and restart but I keep getting a message to type my password so cDock utilize my computer.  I've typed my admin password but it won't take it.  I'm not sure what other password it wants.  Can you help me?
Florian

**Comment by JayBrown** [comment]
In Recovery Mode you must ignore the main window and select Terminal from the "Utilities" menu instead.

**Comment by w0lfschild** [comment]
I'm not sure I can help this sounds unrelated to cDock. I'd double check System Integrity Protection is off and maybe try using a different account when installing SIMBL?
