### ISSUE TITLE
cDock 0.10.1 and 0.10.2 update issues

### ISSUE THREAD

**Issue by recuerom** [w0lfschild/cDock#65]
For the last 3-4 days (and perhaps since updating to 0.10.2 automatically) I can't make use of the CHECK FOR UPDATES option.

Invoking it seems to work but always comes up with UPDATE ERROR (An error has occurred with the update, try again later). Program works fine, just update is not getting thru it seems.

Is the update site down or is there a bug ?

Build date is Feb 02 2016, SIMBL is 0.9.10, Bundle 0.11.2

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/cDock2/issues/21
