### ISSUE TITLE
cDock not working properly with 10.12 Sierra

### ISSUE THREAD

**Issue by lenn5** [w0lfschild/cDock#68]
I can't get the transparent theme to work on cDock running 10.12 Sierra beta. I can only get the dark themed dock to work.

**Comment by w0lfschild** [comment]
It will be updated. The dock doesn't seem to have changed much. Basically need to change an `==` to `>=`.

**Comment by lenn5** [comment]
I just downloaded cDock 0.11.3 and it's still not working correctly on
10.12 beta.

**Comment by w0lfschild** [comment]
Yeah 0.11.3 wasn't really ready. Probably be a little bit before something comes out for Sierra but it should definitely be ready before the public release.

**Comment by usego1** [comment]
läuft Version 12.1  auf 10.12 ?/ does V 12.1 of Cdock Work on 10.12 ??  Vielen Dank für das Geile Programm ! Thanks a lot For this Randy program!!!

**Comment by giantspeck** [comment]
Just updated to 10.12 this morning and cDock is functional, but will not properly apply background images or colors.

**Comment by theqse** [comment]
Hi, is cDock for Sierra ready yet?

**Comment by ManOnHorse** [comment]
cDock2 0.10.3  bundle 0.11.2 SIMBL 0.9.10 feb 05 2016
is not working on OS Sierra 10.12.
I installed witch SIP unabled.

**Comment by DustyWhite** [comment]
I just upgraded to Sierra and now my 3D dock is flat and looks like crap. How can I get the 3D dock back? I can pay for a cDock upgrade if I need. (I really hate the flat OS dock)

**Comment by giantspeck** [comment]
1. Open your **Applications** folder.
2. Right-click **cDock.app** and select **Show Package Contents**. 
3. Navigate to the **Resources** folder.
4. Copy **cDock.bundle**.
5. Go to your hard-drive folder (usually **Macintosh HD** unless you've renamed it).
6. Open the **Library** folder.
7. Open the **Application Resources** folder.
8. Open the **SIMBL** folder.
9. Paste the **cDock.bundle** file into this folder.
10.  Try to restart cDock.  If that doesn't work, try restarting your computer.

**Comment by theqse** [comment]
Hey man!  

I got the latest one 12.1, I think and it works fine. :)

Thanks for coming back to me, though. :)  

Thanks very much for gifting me your time!  

Frederick Malouf








































T H E Q S E
B O N D I   B E A C H   R A D I O  |  T U E S D A Y S  1 6 0 0 - 1 8 0 0   A E S T / A E D T
E M A I L  |  F A C E T I M E  |  I M E S S A G E  -  T H E Q S E @ G M A I L . C O M
F A C E B O O K  |  T W I T T E R  |  V I M E O  -  T H E Q S E
P O  B O X  7 4 3 4    B O N D I  B E A C H    N S W   2 0 2 6
+ 6 1   4 0 3   9 9 3   6 9 9

























































How would I define myself? That’s like asking the definition of infinity …..

**Comment by DustyWhite** [comment]
I was able to do all of that. I still have a flat dock.

What settings should I be using to get my 3D dock? I am trying the various 3D themes and various frost and clear layers. Am I missing something?

Thanks in advance.

Dusty White
me@dustywhite.net
 
I am here to help. If you are lost, stuck, or bored with your metaphysical progress let’s get you better results.

**Comment by ManOnHorse** [comment]
net versie 12.1 geinstallerd en alles werkt prima

**Comment by DustyWhite** [comment]
(Google translattion: "just install version 12.1 and everything works fine")

Reply: I have cDock on AUTO-UPDATE. 

**Attached are two screenshots:** One showing the version I am using and the other showing the settings.

_How do I fix this please?_

Thank you :-)


![unspecified](https://cloud.githubusercontent.com/assets/22549304/19015767/694a87fe-87bf-11e6-9e61-25882f0b7e2d.png)
![unspecified-1](https://cloud.githubusercontent.com/assets/22549304/19015768/6c84ae72-87bf-11e6-82b2-c749f8d3bd6b.png)

**Comment by DustyWhite** [comment]
P.S. I already donated. Will donate again if this can get fixed.

**Comment by w0lfschild** [comment]
Try unchecking show frost layer?

**Comment by DustyWhite** [comment]
Right!

Thanks, so everything works (I played around with all of the settings. As promised, I will make another donation to help the cause.

I seem to remember that I was able to change the hue of the dock itself before. not just “light" and “dark” and other possibilities. I can’t find a way to choose and change the color of the dock itself (like I can with the icon indicators for example). Is that possible?

For example mine is a whitish silver. I want to change it to a greenish hue.

**Comment by w0lfschild** [comment]
There isn't functionality to change the color of the 3D dock.

**Comment by weinschela** [comment]
Where can I find 12.1 to download?    Trying everything in Sierra to get back transparency but so far failure.

**Comment by w0lfschild** [comment]
cDock should automatically update.

https://github.com/w0lfschild/app_updates/tree/master/cDock

Have you disabled system integrity protection?

**Comment by weinschela** [comment]
Yes SIP disabled.  Running 12.2 in Sierra now and nothing is working.  All suggestions welcome.

**Comment by weinschela** [comment]
Hello Woflgang. I am attaching crash report.

**Comment by weinschela** [comment]
Dear Wolfgang,   I did a thorough uninstall including hidden files, and reinstall, and that has fixed it.   I’m going to make another donation to help keep this nice little program going.

alan

**Comment by w0lfschild** [comment]
@weinschela Thanks, glad you were able to get it working.

**Comment by robinkanters** [comment]
Manually updating from the GitHub releases solved all issues for me

**Comment by changmarin** [comment]
Followed the intructions: boot to Recovery, terminal in menu bar, disable.  Back in business here, alles ging gut!

**Comment by swattw** [comment]
How can I make it 3D in High Sierra
I've tried every selction but it doesn't work.
![2017-10-17 9 12 10](https://user-images.githubusercontent.com/19372998/31642059-781d6376-b2ae-11e7-9c37-6140af7183e0.png)

**Comment by user928** [comment]
Thanks @giantspeck ! 
On High Sierra 10.13.4 this fixed my problem (background colors not applying)

> Open your Applications folder.
> Right-click cDock.app and select Show Package Contents.
> Navigate to the Resources folder.
> Copy cDock.bundle.
> Go to folder /Library/Application Support/SIMBL/Plugins
> Paste the cDock.bundle file into this folder.
> Try to restart cDock. If that doesn't work, try restarting your computer.
