### ISSUE TITLE
El Capitan 10.11

### ISSUE THREAD

**Issue by w0lfschild** [w0lfschild/cDock#7]
Post if you're having issues.

**Comment by arathael** [comment]
Yeah it broke when updating osx.

**Comment by lenn5** [comment]
not working in the latest 10.11 beta.

**Comment by w0lfschild** [comment]
Yeah it's not gonna just start working. If the look of the dock really burns your corneas too badly you can replace the dock app with the one from Yosemite but otherwise cDock isn't gonna do anything on El Capitan.

**Comment by lenn5** [comment]
replace dock app with the one from yosemite? how is this done?
thx

**Comment by w0lfschild** [comment]
Copy & Paste or any other form of moving obviously.

/System/Library/CoreServices/Dock.app

**Comment by Chriz007** [comment]
Do you guys know why exactly they are restricting privileges to app developers? Why the sudden change? Isn't it up to the user to decide whether or not he/she wants to customize their mac?

**Comment by lenn5** [comment]
supposedly all in the name of security Chriz.

**Comment by w0lfschild** [comment]
@Chriz007 

I don't believe Apple is 'restricting privileges to app developers'. The point on SIP is to keep users systems safe and secure. The only apps that are going to need to modify the things protected by SIP are generally things Apple wouldn't be endorsing/supporting in the first place.

Also you're still in control because any user can turn off SIP.

As for "Can I change this manually?" and "Where do I access cdock's dock folders?", I'm not really sure what you're asking with either of those questions. cDock isn't a custom Dock application, it injects into the Dock application. The reason it no longer works is because the methods it hooks into no longer exist and/or have been changed.

**Comment by w0lfschild** [comment]
Test 10.11 support. 
- Super janky
- https://github.com/w0lfschild/cDock/releases/tag/v8.3

**Comment by Chriz007** [comment]
Thank you so much! Its fixed now.

**Comment by Chriz007** [comment]
EDIT: I take that back. Its half fixed. When I want to add something to the dock, the dock automatically hides itself. It won't let me change/remove icons

**Comment by w0lfschild** [comment]
cDock is now 100% compatible with 10.9 through 10.11

**Comment by lenn5** [comment]
Thanks! Where can the latest cDock app be found?

**Comment by w0lfschild** [comment]
Opening cDock will check for updates.

**Comment by lenn5** [comment]
I just did that. It installed cDock 9.1.1. But when i tried to change the
dock theme to 10.8 or transparent I still get the standard El Capitan grey
dock.

**Comment by w0lfschild** [comment]
10.8 isn't a theme anymore. 

Is cDock loading? Open console and search for Dock. You should see these messages if cDock is working:

    OS X 10.11, cDock loaded...
    Shadows and reflections initialized...

**Comment by lenn5** [comment]
cDock is loading. I can't find those messages in the console logs. I did
find this though.
[image: Inline image 1]
And the cDock 9.1.2 window is still listing 10.8 as a theme.[image: Inline
image 2]

**Comment by lenn5** [comment]
ok. i booted into recovery and and turned off SIP and rebooted. it seems to
be working now.

**Comment by w0lfschild** [comment]
...

**Comment by aaronhyperum** [comment]
On the latest El Capitan while rootless is disabled, cDock theming/dark mode doesn't work.

**Comment by aaronhyperum** [comment]
cDock is not working. SIP off, SIMBL installed, cDock 2 installed, theming doesn't work. Also, whenever 'apply' in settings is clicked, all the original apps in the dock are added back and your current ones are removed.

**Comment by w0lfschild** [comment]
@aaronhyperum 

Sounds like you probably have some issues unrelated to cDock. The second problem you stated sounds like your com.apple.dock.plist is not saving properly or something.

Make sure you're using the latest version. What do you get when you type this in console?

```
/usr/libexec/PlistBuddy -c "print CFBundleVersion" /Library/Application\ Support/SIMBL/Plugins/cDock.bundle/Contents/Info.plist
```

**Comment by aaronhyperum** [comment]
0.10.1911

About the latest version - I think I have it, but I can't be sure if cDock is always downloading it as I open the app. Any reason for this to happen?

**Comment by dkfiresky** [comment]
@aaronhyperum
> What do you get when you type this in console?
```sh
/usr/libexec/PlistBuddy -c "print CFBundleVersion" /Library/Application\ Support/SIMBL/Plugins/cDock.bundle/Contents/Info.plist
```

**Comment by w0lfschild** [comment]
@aaronhyperum 

The result should be 2012 not 0.10.1911

Get the latest version here: https://github.com/w0lfschild/cDock2/releases/latest

Check this thread: https://github.com/w0lfschild/cDock/issues/34#issuecomment-172354364

**Comment by aaronhyperum** [comment]
OK, now, it's 2012. I still have problems:

For the tab 'Dock Settings', nothing seems to work but the 'reset button'. I changed the 'autohide' setting, clicked, apply, and got 2 (two) console messages.

```
1/18/16 4:15:47.776 PM cDock 2[66126]: *** -[__NSArrayI objectAtIndex:]: index 18446744073709551615 beyond bounds [0 .. 2]
```
and
```
1/18/16 4:15:47.779 PM cDock 2[66126]: (
	0   CoreFoundation                      0x00007fff90aa1ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff85aaf73c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9096c554 -[__NSArrayI objectAtIndex:] + 164
	3   cDock 2                             0x0000000102b3dc32 -[AppDelegate applyDockChanges:] + 6946
	4   libsystem_trace.dylib               0x00007fff8b9f107a _os_activity_initiate + 75
	5   AppKit                              0x00007fff8ff3a51d -[NSApplication sendAction:to:from:] + 460
	6   AppKit                              0x00007fff8ff4f486 -[NSControl sendAction:to:] + 86
	7   AppKit                              0x00007fff8ff4f3b0 __26-[NSCell _sendActionFrom:]_block_invoke + 131
	8   libsystem_trace.dylib               0x00007fff8b9f107a _os_activity_initiate + 75
	9   AppKit                              0x00007fff8ff4f30d -[NSCell _sendActionFrom:] + 144
	10  libsystem_trace.dylib               0x00007fff8b9f107a _os_activity_initiate + 75
	11  AppKit                              0x00007fff8ff4d932 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 2693
	12  AppKit                              0x00007fff8ffa2d58 -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 744
	13  AppKit                              0x00007fff8ff4c05c -[NSControl mouseDown:] + 669
	14  AppKit                              0x00007fff904f9d1d -[NSWindow _handleMouseDownEvent:isDelayedEvent:] + 6322
	15  AppKit                              0x00007fff904fafad -[NSWindow _reallySendEvent:isDelayedEvent:] + 212
	16  AppKit                              0x00007fff8fe53735 -[NSWindow sendEvent:] + 517
	17  AppKit                              0x00007fff8fe4fe49 -[NSApplication sendEvent:] + 2540
	18  AppKit                              0x00007fff8fd8303a -[NSApplication run] + 796
	19  AppKit                              0x00007fff8fd05520 NSApplicationMain + 1176
	20  cDock 2                             0x0000000102b551b2 main + 34
	21  libdyld.dylib                       0x00007fff8a4a45ad start + 1
)
```

I looked at the comment you pointed me too. I followed the steps by setting 'everyone' to 'read and write' and relaunched. Theming and Dock Settings still didn't work, but I found something that could be of interest when the app started.

```
1/18/16 4:21:42.327 PM com.apple.xpc.launchd[1]: (org.w0lf.cDockAgent.269472[66143]) Service exited due to signal: Terminated: 15
```

Any insight?

**Comment by aaronhyperum** [comment]
I deleted SIMBL's files, including Application Support. Theming now works fine, but Dock Settings is still broken. The [really huge number] beyond bounds [0 .. 2] error in console still occurs when Apply is clicked.

**Comment by w0lfschild** [comment]
@aaronhyperum not sure what's causing that, maybe reset your dock plist with the reset button.
