### ISSUE TITLE
Theme won't change

### ISSUE THREAD

**Issue by github-administrator** [w0lfschild/cDock#72]
When I select any theme and press apply, it quits the app and nothing happens.

**Comment by w0lfschild** [comment]
What version of cDock are you using?

**Comment by github-administrator** [comment]
6.06 (When I press about cDock)

**Comment by w0lfschild** [comment]
@github-administrator that is really old. Use the latest version.

**Comment by github-administrator** [comment]
I would use cDock2 but it requires a admin password to install SIMBL.

**Comment by w0lfschild** [comment]
Well that's all that works anymore since https://support.apple.com/en-us/HT204942

It's simply a requirement for it to work, just like disabling System Integrity Protection is on El Capitan and above.
