### ISSUE TITLE
Icons are all darkened except open ones 

### ISSUE THREAD

**Issue by Mv826** [w0lfschild/cDock#73]
![screen shot 2016-08-27 at 5 10 08 pm](https://cloud.githubusercontent.com/assets/13159207/18030106/2436d99e-6c79-11e6-812f-77099777044d.png)

Refer to screenshot

Temp fix is using the option darken icons on mouse-over but you have to leave this effect enabled

**Comment by w0lfschild** [comment]
I've put out 0.12.1 hopefully that should fix things up.

**Comment by Mv826** [comment]
Thank you, the problem has been resolved!
