### ISSUE TITLE
Dock overlaps other applications

### ISSUE THREAD

**Issue by Mv826** [w0lfschild/cDock#74]
![screen shot 2016-08-27 at 5 13 01 pm](https://cloud.githubusercontent.com/assets/13159207/18030131/c0b5ca14-6c79-11e6-8030-3b91390671b0.png)

Refer to screenshot

This issue is from older versions of cDock but just thought I'd bring it to attention in the meantime

cDock slightly overlaps other application windows; temp fix is manually changing size of app windows to prevent the overlap

**Comment by w0lfschild** [comment]
I'm pretty sure you already posted this same issue a while ago. https://github.com/w0lfschild/cDock/issues/66

I'll look into it at some point.
