### ISSUE TITLE
SIMBL install failed

### ISSUE THREAD

**Issue by Jayip** [w0lfschild/cDock#75]
Hi. Since the last update to 0.12.1 I keep getting the message "SIMBL install failed" when starting or restarting cDock.  Also doesn't get transparent fully - more like "translucent". Running on MacOS 10.11.6. Thanks

Jay

**Comment by Jayip** [comment]
So I resolved the SIMBL issue - i had not disabled the protection. I still am not getting the transparent dock and actually none of the changes take place - no matter what setting I choose. I am restarting the dock after each adjustment.

**Comment by Jayip** [comment]
Actually - I take that back - when I re-enabled SIP after the cDock install it shows the SIMBL.oasx failed issue again

**Comment by w0lfschild** [comment]
Make sure the SIMBL.osax is actually being installed at /System/Library/ScriptingAdditions/SIMBL.osax

**Comment by Bert51** [comment]
I made the same mistake when upgrading to 0.12.4.  My solution was to download 0.12.4 from MacUpdate at https://www.macupdate.com/app/mac/51149/cdock, disbale SIP, install cDock 0.12.4, and re-enable SIP.  Now, all is well.  I am running macOS Sierra 10.12.
