### ISSUE TITLE
Transparency not working!

### ISSUE THREAD

**Issue by edkopec** [w0lfschild/cDock#77]
Transparency not working with OSX 10.12.1

**Comment by w0lfschild** [comment]
Are any themes working for you? I'm guessing something just hasn't been installed properly or failed to install.

**Comment by olap1200** [comment]
not working

**Comment by w0lfschild** [comment]
@olap1200 are any themes working for you? Is SIMBL actually installed?

**Comment by olap1200** [comment]
dark 2D works, 3D themes doesn't and them look the same as 2D themes. SIMBL installed.

**Comment by w0lfschild** [comment]
Try deleting the themes folder and re-opening cDock.

You can go to the themes tab in the menubar to delete the themes or do it via Finder.
