### ISSUE TITLE
Dock Tab and Application Spacers 

### ISSUE THREAD

**Issue by HelixSoundLab** [w0lfschild/cDock#81]
I've noticed on Sierra and El Capitan that the "Dock" tab functions will not apply. Is there a known fix for this?

**Comment by w0lfschild** [comment]
Should be working. Most likely there is an issue writing to your Dock plist file `~/Library/Preferences/com.apple.dock.plist`.

**Comment by HelixSoundLab** [comment]
I figured out a work around. Once you set the dock position to left then back to bottom, that tab works. Just letting you know. Love the program. It's great!    
  
  
  
  
  

  
  
>
