### ISSUE TITLE
update/quit problem

### ISSUE THREAD

**Issue by UrbanProse** [w0lfschild/cDock#82]
Using cDock version 0.10.1 on a 15" 2011 MacBook Pro running macOS 10.10.5 (Yosemite).  

My dock has been managed nicely by cDock for a couple of years, but now I can't get cDock to open to check for updates.  Attempts to launch it always generate a message that says "cDock quit unexpectedly."  I've found nothing on the web related to how to fix that launch problem, or how to update the version I have without launching cDock successfully.  

Can you (1) help me get cDock to launch properly on the system described above, and (2) explain how to update it if it won't launch properly?  Thanks.

**Comment by w0lfschild** [comment]
Download the latest release : https://github.com/w0lfschild/app_updates/raw/master/cDock/cDock_0.12.4.zip
