### ISSUE TITLE
Not working in El Capitan on a mid-2007 iMac/trouble finding activation

### ISSUE THREAD

**Issue by fizdog** [w0lfschild/cDock#85]
I was looking for a way to customize my iMac and i came across your neat little app. I disabled SIP and nothing is working. I also purchased your app and i can't find how to activate it.

**Comment by w0lfschild** [comment]
Check out the latest version.

Maybe just doing a reboot and double checking that System Integrity Protection is for sure off would be my first steps for troubleshooting. 

I would also check if the bundle and osax are being installed, both are required for theming to work.

`/System/Library/ScriptingAdditions/SIMBL.osax`
`/Library/Application Support/SIMBL/Plugins/cDock.bundle`

To activate the application just click the activate or purchase buttons in the sidebar.
