### ISSUE TITLE
CDock

### ISSUE THREAD

**Issue by eddie7172** [w0lfschild/cDock#90]
What should I do if I update MacOs 11Big sur to start cdock and cause the screen to flicker?

**Comment by eddie7172** [comment]
開發者～我在Big sur 不敢使用CDock因爲又怕螢幕閃頻

**Comment by eddie7172** [comment]
Developer~ I dare not use CDock in Big sur because I am afraid of screen flickering

**Comment by w0lfschild** [comment]
To use cDock on Big Sur you have to use version 4.4.3 or newer.

If you're using version 3 you can stop the Dock from crashing by deleting `/Library/Application Support/MacEnhance/Plugins/cDock.bundle`. Or by opening Activity monitor and closing `cDock Helper`.
