### ISSUE TITLE
I've noticed it says cDock requires 10.10 or higher. I'm running 10.13.6 and it says that I need 10.14 to run it. Can I get an older download from anywhere?

### ISSUE THREAD

**Issue by KnudsonBlita** [w0lfschild/cDock#91]

**Comment by w0lfschild** [comment]
[You can get old links here](https://www.macenhance.com/docs/cdock/changes)

**Comment by KnudsonBlita** [comment]
Thanks

**Comment by KnudsonBlita** [comment]
Well I followed said link, and "404 not found".

**Comment by w0lfschild** [comment]
Curious. You could try it with .html at the end.

https://www.macenhance.com/docs/cdock/changes.html

**Comment by KnudsonBlita** [comment]
Okay I was able to get it to work. Thanks for providing this cool software. I hate the MacOs flat dock.
